# Generated by Django 5.2.1 on 2025-07-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['setor', 'titulo'], 'permissions': [('view_all_dashboards', 'Can view all dashboards')]},
        ),
    ]
