# Generated by Django 5.2.1 on 2025-08-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashboards', '0003_dashboard_favoritado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='iframe',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo HTML'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
