# Generated by Django 5.2.1 on 2025-08-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashboards', '0004_dashboard_iframe_alter_dashboard_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='iframe',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
