# Generated by Django 5.2.1 on 2025-11-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashboards', '0005_remove_dashboard_iframe_dashboard_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='em_dev',
            field=models.BooleanField(default=True, verbose_name='Em desenvolvimento'),
        ),
    ]
