# Generated by Django 5.2.1 on 2025-11-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_dashboards', '0006_dashboard_em_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='em_manutencao',
            field=models.BooleanField(default=False, verbose_name='Em manutenção'),
        ),
    ]
