# Generated by Django 5.2.1 on 2025-06-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_ramais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramais',
            name='maquina',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
