# Generated by Django 5.2.1 on 2026-02-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_ramais', '0002_alter_ramais_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramais',
            name='maquina',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ramais',
            name='ramal',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
