# Generated by Django 5.2.1 on 2025-07-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_calendar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
