# Generated by Django 5.2.1 on 2025-07-16 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_calendar', '0002_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True, verbose_name='Tipo da Reunião')),
                ('cor', models.CharField(default='#007bff', max_length=7, verbose_name='Cor em Hexadecimal')),
            ],
            options={
                'verbose_name': 'tipo de reunião',
                'verbose_name_plural': 'tipos de reunião',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('organizador', models.CharField(max_length=200, verbose_name='Organizador')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_inicio', models.DateTimeField(verbose_name='Data e Hora de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data e Hora de Fim')),
                ('privada', models.BooleanField(default=False, verbose_name='Reunião Privada?')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_calendar.tiporeuniao', verbose_name='Tipo de Reunião')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['data_inicio'],
            },
        ),
    ]
