# Generated by Django 5.2.1 on 2025-07-18 01:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_calendar', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporeuniao',
            name='cor',
            field=colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None, verbose_name='Cor do Tipo de Reunião'),
        ),
    ]
