# Generated by Django 5.2.1 on 2025-07-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_calendar', '0005_remove_agenda_organizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_calendar.tiporeuniao', verbose_name='Tipo de Reunião'),
        ),
    ]
